services:
  assignment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npx prisma generate && npm run dev"
